# permissions for end users to edit pipelineschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelineschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: pipelineschedule-editor-role
rules:
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineschedules/status
  verbs:
  - get
