---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - tdsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - tdsets/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - tdsets/status
  verbs:
  - get
  - patch
  - update
