---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinedefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinedefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinejobs/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelinejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineschedules/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.k-pipe.cloud
  resources:
  - pipelineschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schedule.kpipe
  resources:
  - tdsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schedule.kpipe
  resources:
  - tdsets/finalizers
  verbs:
  - update
- apiGroups:
  - schedule.kpipe
  resources:
  - tdsets/status
  verbs:
  - get
  - patch
  - update
